/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AllOfUserTaskListResponseOwner model module.
 * @module model/AllOfUserTaskListResponseOwner
 * @version 2.0.1
 */
export class AllOfUserTaskListResponseOwner {
  /**
   * Constructs a new <code>AllOfUserTaskListResponseOwner</code>.
   * The owner of the user task list, i.e. the person whose My Tasks is represented by this resource.
   * @alias module:model/AllOfUserTaskListResponseOwner
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AllOfUserTaskListResponseOwner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfUserTaskListResponseOwner} obj Optional instance to populate.
   * @return {module:model/AllOfUserTaskListResponseOwner} The populated <code>AllOfUserTaskListResponseOwner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfUserTaskListResponseOwner();
    }
    return obj;
  }
}
