/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse412Errors model module.
 * @module model/InlineResponse412Errors
 * @version 2.0.5
 */
export class InlineResponse412Errors {
  /**
   * Constructs a new <code>InlineResponse412Errors</code>.
   * @alias module:model/InlineResponse412Errors
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse412Errors</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse412Errors} obj Optional instance to populate.
   * @return {module:model/InlineResponse412Errors} The populated <code>InlineResponse412Errors</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse412Errors();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }
}

/**
 * Message providing more detail about the error that occurred, if available.
 * @member {String} message
 */
InlineResponse412Errors.prototype.message = undefined;

