/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ModifyDependentsRequest model module.
 * @module model/ModifyDependentsRequest
 * @version 2.0.6
 */
export class ModifyDependentsRequest {
  /**
   * Constructs a new <code>ModifyDependentsRequest</code>.
   * A set of dependent tasks.
   * @alias module:model/ModifyDependentsRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModifyDependentsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModifyDependentsRequest} obj Optional instance to populate.
   * @return {module:model/ModifyDependentsRequest} The populated <code>ModifyDependentsRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModifyDependentsRequest();
      if (data.hasOwnProperty('dependents'))
        obj.dependents = ApiClient.convertToType(data['dependents'], ['String']);
    }
    return obj;
  }
}

/**
 * An array of task gids that are dependents of the given task.
 * @member {Array.<String>} dependents
 */
ModifyDependentsRequest.prototype.dependents = undefined;

