/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NextPage model module.
 * @module model/NextPage
 * @version 2.0.6
 */
export class NextPage {
  /**
   * Constructs a new <code>NextPage</code>.
   * *Conditional*. This property is only present when a limit query parameter is provided in the request. When making a paginated request, the API will return a number of results as specified by the limit parameter. If more results exist, then the response will contain a next_page attribute, which will include an offset, a relative path attribute, and a full uri attribute. If there are no more pages available, next_page will be null and no offset will be provided. Note that an offset token will expire after some time, as data may have changed.
   * @alias module:model/NextPage
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NextPage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NextPage} obj Optional instance to populate.
   * @return {module:model/NextPage} The populated <code>NextPage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NextPage();
      if (data.hasOwnProperty('offset'))
        obj.offset = ApiClient.convertToType(data['offset'], 'String');
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('uri'))
        obj.uri = ApiClient.convertToType(data['uri'], 'String');
    }
    return obj;
  }
}

/**
 * Pagination offset for the request.
 * @member {String} offset
 */
NextPage.prototype.offset = undefined;

/**
 * A relative path containing the query parameters to fetch for next_page
 * @member {String} path
 */
NextPage.prototype.path = undefined;

/**
 * A full uri containing the query parameters to fetch for next_page
 * @member {String} uri
 */
NextPage.prototype.uri = undefined;

