/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TaskSetParentRequest model module.
 * @module model/TaskSetParentRequest
 * @version 2.0.6
 */
export class TaskSetParentRequest {
  /**
   * Constructs a new <code>TaskSetParentRequest</code>.
   * @alias module:model/TaskSetParentRequest
   * @class
   * @param parent {String} The new parent of the task, or `null` for no parent.
   */
  constructor(parent) {
    this.parent = parent;
  }

  /**
   * Constructs a <code>TaskSetParentRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TaskSetParentRequest} obj Optional instance to populate.
   * @return {module:model/TaskSetParentRequest} The populated <code>TaskSetParentRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TaskSetParentRequest();
      if (data.hasOwnProperty('parent'))
        obj.parent = ApiClient.convertToType(data['parent'], 'String');
      if (data.hasOwnProperty('insert_after'))
        obj.insert_after = ApiClient.convertToType(data['insert_after'], 'String');
      if (data.hasOwnProperty('insert_before'))
        obj.insert_before = ApiClient.convertToType(data['insert_before'], 'String');
    }
    return obj;
  }
}

/**
 * The new parent of the task, or `null` for no parent.
 * @member {String} parent
 */
TaskSetParentRequest.prototype.parent = undefined;

/**
 * A subtask of the parent to insert the task after, or `null` to insert at the beginning of the list.
 * @member {String} insert_after
 */
TaskSetParentRequest.prototype.insert_after = undefined;

/**
 * A subtask of the parent to insert the task before, or `null` to insert at the end of the list.
 * @member {String} insert_before
 */
TaskSetParentRequest.prototype.insert_before = undefined;

