/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {WebhookRequestFilters} from './WebhookRequestFilters';

/**
 * The WebhookUpdateRequest model module.
 * @module model/WebhookUpdateRequest
 * @version 2.0.6
 */
export class WebhookUpdateRequest {
  /**
   * Constructs a new <code>WebhookUpdateRequest</code>.
   * @alias module:model/WebhookUpdateRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WebhookUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookUpdateRequest} obj Optional instance to populate.
   * @return {module:model/WebhookUpdateRequest} The populated <code>WebhookUpdateRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WebhookUpdateRequest();
      if (data.hasOwnProperty('filters'))
        obj.filters = ApiClient.convertToType(data['filters'], [WebhookRequestFilters]);
    }
    return obj;
  }
}

/**
 * An array of WebhookFilter objects to specify a whitelist of filters to apply to events from this webhook. If a webhook event passes any of the filters the event will be delivered; otherwise no event will be sent to the receiving server.
 * @member {Array.<module:model/WebhookRequestFilters>} filters
 */
WebhookUpdateRequest.prototype.filters = undefined;

