/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";
import Collection = require("../utils/collection");

/**
* AIStudioUsageAPI service.
* @module api/AIStudioUsageAPIApi
* @version 3.2.0
*/
export class AIStudioUsageAPIApi {
    /**
    * Constructs a new AIStudioUsageAPIApi.
    * @alias module:api/AIStudioUsageAPIApi
    * @class
    * @param apiClient Optional API client implementation to use, default to ApiClient.instance if unspecified.
    */
    constructor(apiClient?: ApiClient);

    apiClient: ApiClient;

    /**
     * Get AI Studio credit utilization
     * Returns one row per AI Studio run (rule execution) for the workspace, in ascending order (oldest first) so that incremental consumers can poll forward. Each row describes what ran, who it is attributed to, the model used, and the credits consumed.  Credit data is available from January 8th, 2025 onward, and is queryable for the full history since then (there is no limit on how far back you can query). A &#x60;start_at&#x60; earlier than January 8th, 2025 is silently clamped; it is not an error.  The list is always [paginated](/docs/pagination). When more results exist, the response includes a &#x60;next_page&#x60; with an &#x60;offset&#x60; that can be used to retrieve the next set of rows. The row &#x60;gid&#x60; is stable and can be used to de-duplicate rows across incremental loads.  This endpoint is restricted to [service accounts](https://help.asana.com/s/article/service-accounts) in organizations licensed for AI Studio.
     * @param workspace_gid Globally unique identifier for the workspace or organization.
     * @param opts Optional parameters
     * @param opts.start_at Inclusive lower bound. Runs are ordered and filtered by when their usage was recorded (the monotonic timestamp used for incremental polling), not by &#x60;run_started_at&#x60;. Omitted ⇒ the 2025-01-08 floor — no credit data exists before then, and there is no limit on how far back you can query. A value earlier than 2025-01-08 is treated as 2025-01-08 (not rejected), matching the audit log.
     * @param opts.end_at Filter to runs whose usage was recorded before this time (exclusive) — by when the run&#x27;s credit usage was recorded, not by &#x60;run_started_at&#x60;. Defaults to the time of the request.
     * @param opts.division_gid Scope results to a single division (its gid). Omitted ⇒ the org&#x27;s first licensed division. Use this to retrieve only one division&#x27;s slice (e.g. for a division-level admin or billing owner) rather than the whole organization.
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @returns A Promise, with an object containing data and HTTP response
     */
    getAiStudioRunsWithHttpInfo(workspace_gid: string, opts?: { 'start_at'?: any; 'end_at'?: any; 'division_gid'?: string; 'limit'?: any; 'offset'?: string;  }): Promise<Collection | { response: any; data: any }>;

    /**
     * Get AI Studio credit utilization
     * Returns one row per AI Studio run (rule execution) for the workspace, in ascending order (oldest first) so that incremental consumers can poll forward. Each row describes what ran, who it is attributed to, the model used, and the credits consumed.  Credit data is available from January 8th, 2025 onward, and is queryable for the full history since then (there is no limit on how far back you can query). A &#x60;start_at&#x60; earlier than January 8th, 2025 is silently clamped; it is not an error.  The list is always [paginated](/docs/pagination). When more results exist, the response includes a &#x60;next_page&#x60; with an &#x60;offset&#x60; that can be used to retrieve the next set of rows. The row &#x60;gid&#x60; is stable and can be used to de-duplicate rows across incremental loads.  This endpoint is restricted to [service accounts](https://help.asana.com/s/article/service-accounts) in organizations licensed for AI Studio.
     * @param workspace_gid Globally unique identifier for the workspace or organization.
     * @param opts Optional parameters
     * @param opts.start_at Inclusive lower bound. Runs are ordered and filtered by when their usage was recorded (the monotonic timestamp used for incremental polling), not by &#x60;run_started_at&#x60;. Omitted ⇒ the 2025-01-08 floor — no credit data exists before then, and there is no limit on how far back you can query. A value earlier than 2025-01-08 is treated as 2025-01-08 (not rejected), matching the audit log.
     * @param opts.end_at Filter to runs whose usage was recorded before this time (exclusive) — by when the run&#x27;s credit usage was recorded, not by &#x60;run_started_at&#x60;. Defaults to the time of the request.
     * @param opts.division_gid Scope results to a single division (its gid). Omitted ⇒ the org&#x27;s first licensed division. Use this to retrieve only one division&#x27;s slice (e.g. for a division-level admin or billing owner) rather than the whole organization.
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @returns A Promise
     */
    getAiStudioRuns(workspace_gid: string, opts?: { 'start_at'?: any; 'end_at'?: any; 'division_gid'?: string; 'limit'?: any; 'offset'?: string;  }): Promise<Collection | any>;

    /**
     * Get AI Studio seats
     * Returns a current snapshot of AI Studio seat allocations for the workspace — who has access, at what license tier, and the state of each seat. This is a point-in-time snapshot; customers build their own history tables on top of periodic pulls.  The list is always [paginated](/docs/pagination). When more results exist, the response includes a &#x60;next_page&#x60; with an &#x60;offset&#x60; that can be used to retrieve the next set of rows.  This endpoint is restricted to [service accounts](https://help.asana.com/s/article/service-accounts) in organizations licensed for AI Studio.
     * @param workspace_gid Globally unique identifier for the workspace or organization.
     * @param opts Optional parameters
     * @param opts.state Filter seats to this state.
     * @param opts.division_gid Scope results to a single division (its gid). Omitted ⇒ the org&#x27;s first licensed division. Use this to retrieve only one division&#x27;s slice (e.g. for a division-level admin or billing owner) rather than the whole organization.
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @returns A Promise, with an object containing data and HTTP response
     */
    getAiStudioSeatsWithHttpInfo(workspace_gid: string, opts?: { 'state'?: string; 'division_gid'?: string; 'limit'?: any; 'offset'?: string;  }): Promise<Collection | { response: any; data: any }>;

    /**
     * Get AI Studio seats
     * Returns a current snapshot of AI Studio seat allocations for the workspace — who has access, at what license tier, and the state of each seat. This is a point-in-time snapshot; customers build their own history tables on top of periodic pulls.  The list is always [paginated](/docs/pagination). When more results exist, the response includes a &#x60;next_page&#x60; with an &#x60;offset&#x60; that can be used to retrieve the next set of rows.  This endpoint is restricted to [service accounts](https://help.asana.com/s/article/service-accounts) in organizations licensed for AI Studio.
     * @param workspace_gid Globally unique identifier for the workspace or organization.
     * @param opts Optional parameters
     * @param opts.state Filter seats to this state.
     * @param opts.division_gid Scope results to a single division (its gid). Omitted ⇒ the org&#x27;s first licensed division. Use this to retrieve only one division&#x27;s slice (e.g. for a division-level admin or billing owner) rather than the whole organization.
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @returns A Promise
     */
    getAiStudioSeats(workspace_gid: string, opts?: { 'state'?: string; 'division_gid'?: string; 'limit'?: any; 'offset'?: string;  }): Promise<Collection | any>;

}
