/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";
import Collection = require("../utils/collection");

/**
* Allocations service.
* @module api/AllocationsApi
* @version 3.1.11
*/
export class AllocationsApi {
    /**
    * Constructs a new AllocationsApi.
    * @alias module:api/AllocationsApi
    * @class
    * @param apiClient Optional API client implementation to use, default to ApiClient.instance if unspecified.
    */
    constructor(apiClient?: ApiClient);

    apiClient: ApiClient;

    /**
     * Create an allocation
     * Creates a new allocation.  Returns the full record of the newly created allocation.
     * @param body The allocation to create.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    createAllocationWithHttpInfo(body: any, opts?: { 'opt_fields'?: any;  }): Promise<{ response: any; data: any }>;

    /**
     * Create an allocation
     * Creates a new allocation.  Returns the full record of the newly created allocation.
     * @param body The allocation to create.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    createAllocation(body: any, opts?: { 'opt_fields'?: any;  }): Promise<any>;

    /**
     * Delete an allocation
     * A specific, existing allocation can be deleted by making a DELETE request on the URL for that allocation.  Returns an empty data record.
     * @param allocation_gid Globally unique identifier for the allocation.
     * @returns A Promise, with an object containing data and HTTP response
     */
    deleteAllocationWithHttpInfo(allocation_gid: string): Promise<{ response: any; data: any }>;

    /**
     * Delete an allocation
     * A specific, existing allocation can be deleted by making a DELETE request on the URL for that allocation.  Returns an empty data record.
     * @param allocation_gid Globally unique identifier for the allocation.
     * @returns A Promise
     */
    deleteAllocation(allocation_gid: string): Promise<any>;

    /**
     * Get an allocation
     * Returns the complete allocation record for a single allocation.
     * @param allocation_gid Globally unique identifier for the allocation.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    getAllocationWithHttpInfo(allocation_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<{ response: any; data: any }>;

    /**
     * Get an allocation
     * Returns the complete allocation record for a single allocation.
     * @param allocation_gid Globally unique identifier for the allocation.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    getAllocation(allocation_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<any>;

    /**
     * Get multiple allocations
     * Returns a list of allocations filtered to a specific project, user or placeholder.
     * @param opts Optional parameters
     * @param opts.parent Globally unique identifier for the project to filter allocations by.
     * @param opts.assignee Globally unique identifier for the user or placeholder the allocation is assigned to.
     * @param opts.workspace Globally unique identifier for the workspace.
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    getAllocationsWithHttpInfo(opts?: { 'parent'?: string; 'assignee'?: string; 'workspace'?: string; 'limit'?: any; 'offset'?: string; 'opt_fields'?: any;  }): Promise<Collection | { response: any; data: any }>;

    /**
     * Get multiple allocations
     * Returns a list of allocations filtered to a specific project, user or placeholder.
     * @param opts Optional parameters
     * @param opts.parent Globally unique identifier for the project to filter allocations by.
     * @param opts.assignee Globally unique identifier for the user or placeholder the allocation is assigned to.
     * @param opts.workspace Globally unique identifier for the workspace.
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    getAllocations(opts?: { 'parent'?: string; 'assignee'?: string; 'workspace'?: string; 'limit'?: any; 'offset'?: string; 'opt_fields'?: any;  }): Promise<Collection | any>;

    /**
     * Update an allocation
     * An existing allocation can be updated by making a PUT request on the URL for that allocation. Only the fields provided in the &#x60;data&#x60; block will be updated; any unspecified fields will remain unchanged.  Returns the complete updated allocation record.
     * @param body The updated fields for the allocation.
     * @param allocation_gid Globally unique identifier for the allocation.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    updateAllocationWithHttpInfo(body: any, allocation_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<{ response: any; data: any }>;

    /**
     * Update an allocation
     * An existing allocation can be updated by making a PUT request on the URL for that allocation. Only the fields provided in the &#x60;data&#x60; block will be updated; any unspecified fields will remain unchanged.  Returns the complete updated allocation record.
     * @param body The updated fields for the allocation.
     * @param allocation_gid Globally unique identifier for the allocation.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    updateAllocation(body: any, allocation_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<any>;

}
