/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";
import Collection = require("../utils/collection");

/**
* CustomFieldSettings service.
* @module api/CustomFieldSettingsApi
* @version 3.1.11
*/
export class CustomFieldSettingsApi {
    /**
    * Constructs a new CustomFieldSettingsApi.
    * @alias module:api/CustomFieldSettingsApi
    * @class
    * @param apiClient Optional API client implementation to use, default to ApiClient.instance if unspecified.
    */
    constructor(apiClient?: ApiClient);

    apiClient: ApiClient;

    /**
     * Get a goal&#x27;s custom fields
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;goals:read&lt;/code&gt;  Returns a list of all of the custom fields settings on a goal, in compact form. Note that, as in all queries to collections which return compact representation, &#x60;opt_fields&#x60; can be used to include more data than is returned in the compact representation. See the [documentation for input/output options](https://developers.asana.com/docs/inputoutput-options) for more information.
     * @param goal_gid Globally unique identifier for the goal.
     * @param opts Optional parameters
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    getCustomFieldSettingsForGoalWithHttpInfo(goal_gid: string, opts?: { 'limit'?: any; 'offset'?: string; 'opt_fields'?: any;  }): Promise<Collection | { response: any; data: any }>;

    /**
     * Get a goal&#x27;s custom fields
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;goals:read&lt;/code&gt;  Returns a list of all of the custom fields settings on a goal, in compact form. Note that, as in all queries to collections which return compact representation, &#x60;opt_fields&#x60; can be used to include more data than is returned in the compact representation. See the [documentation for input/output options](https://developers.asana.com/docs/inputoutput-options) for more information.
     * @param goal_gid Globally unique identifier for the goal.
     * @param opts Optional parameters
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    getCustomFieldSettingsForGoal(goal_gid: string, opts?: { 'limit'?: any; 'offset'?: string; 'opt_fields'?: any;  }): Promise<Collection | any>;

    /**
     * Get a portfolio&#x27;s custom fields
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;portfolios:read&lt;/code&gt;  Returns a list of all of the custom fields settings on a portfolio, in compact form.
     * @param portfolio_gid Globally unique identifier for the portfolio.
     * @param opts Optional parameters
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    getCustomFieldSettingsForPortfolioWithHttpInfo(portfolio_gid: string, opts?: { 'limit'?: any; 'offset'?: string; 'opt_fields'?: any;  }): Promise<Collection | { response: any; data: any }>;

    /**
     * Get a portfolio&#x27;s custom fields
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;portfolios:read&lt;/code&gt;  Returns a list of all of the custom fields settings on a portfolio, in compact form.
     * @param portfolio_gid Globally unique identifier for the portfolio.
     * @param opts Optional parameters
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    getCustomFieldSettingsForPortfolio(portfolio_gid: string, opts?: { 'limit'?: any; 'offset'?: string; 'opt_fields'?: any;  }): Promise<Collection | any>;

    /**
     * Get a project&#x27;s custom fields
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;projects:read&lt;/code&gt;  Returns a list of all of the custom fields settings on a project, in compact form. Note that, as in all queries to collections which return compact representation, &#x60;opt_fields&#x60; can be used to include more data than is returned in the compact representation. See the [documentation for input/output options](https://developers.asana.com/docs/inputoutput-options) for more information.
     * @param project_gid Globally unique identifier for the project.
     * @param opts Optional parameters
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    getCustomFieldSettingsForProjectWithHttpInfo(project_gid: string, opts?: { 'limit'?: any; 'offset'?: string; 'opt_fields'?: any;  }): Promise<Collection | { response: any; data: any }>;

    /**
     * Get a project&#x27;s custom fields
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;projects:read&lt;/code&gt;  Returns a list of all of the custom fields settings on a project, in compact form. Note that, as in all queries to collections which return compact representation, &#x60;opt_fields&#x60; can be used to include more data than is returned in the compact representation. See the [documentation for input/output options](https://developers.asana.com/docs/inputoutput-options) for more information.
     * @param project_gid Globally unique identifier for the project.
     * @param opts Optional parameters
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    getCustomFieldSettingsForProject(project_gid: string, opts?: { 'limit'?: any; 'offset'?: string; 'opt_fields'?: any;  }): Promise<Collection | any>;

    /**
     * Get a team&#x27;s custom fields
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;teams:read&lt;/code&gt;  Returns a list of all of the custom fields settings on a team, in compact form. Note that, as in all queries to collections which return compact representation, &#x60;opt_fields&#x60; can be used to include more data than is returned in the compact representation. See the [documentation for input/output options](https://developers.asana.com/docs/inputoutput-options) for more information.
     * @param team_gid Globally unique identifier for the team.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    getCustomFieldSettingsForTeamWithHttpInfo(team_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<Collection | { response: any; data: any }>;

    /**
     * Get a team&#x27;s custom fields
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;teams:read&lt;/code&gt;  Returns a list of all of the custom fields settings on a team, in compact form. Note that, as in all queries to collections which return compact representation, &#x60;opt_fields&#x60; can be used to include more data than is returned in the compact representation. See the [documentation for input/output options](https://developers.asana.com/docs/inputoutput-options) for more information.
     * @param team_gid Globally unique identifier for the team.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    getCustomFieldSettingsForTeam(team_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<Collection | any>;

}
