/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";
import Collection = require("../utils/collection");

/**
* OooEntries service.
* @module api/OooEntriesApi
* @version 3.2.0
*/
export class OooEntriesApi {
    /**
    * Constructs a new OooEntriesApi.
    * @alias module:api/OooEntriesApi
    * @class
    * @param apiClient Optional API client implementation to use, default to ApiClient.instance if unspecified.
    */
    constructor(apiClient?: ApiClient);

    apiClient: ApiClient;

    /**
     * Create an OOO entry
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;ooo_entries:write&lt;/code&gt;  Creates a new OOO entry.  Returns the full record of the newly created OOO entry.
     * @param body The OOO entry to create.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    createOooEntryWithHttpInfo(body: any, opts?: { 'opt_fields'?: any;  }): Promise<{ response: any; data: any }>;

    /**
     * Create an OOO entry
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;ooo_entries:write&lt;/code&gt;  Creates a new OOO entry.  Returns the full record of the newly created OOO entry.
     * @param body The OOO entry to create.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    createOooEntry(body: any, opts?: { 'opt_fields'?: any;  }): Promise<any>;

    /**
     * Delete an OOO entry
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;ooo_entries:delete&lt;/code&gt;  A specific, existing OOO entry can be deleted by making a DELETE request on the URL for that OOO entry.  Returns an empty data record.
     * @param ooo_entry_gid Globally unique identifier for the OOO entry.
     * @returns A Promise, with an object containing data and HTTP response
     */
    deleteOooEntryWithHttpInfo(ooo_entry_gid: string): Promise<{ response: any; data: any }>;

    /**
     * Delete an OOO entry
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;ooo_entries:delete&lt;/code&gt;  A specific, existing OOO entry can be deleted by making a DELETE request on the URL for that OOO entry.  Returns an empty data record.
     * @param ooo_entry_gid Globally unique identifier for the OOO entry.
     * @returns A Promise
     */
    deleteOooEntry(ooo_entry_gid: string): Promise<any>;

    /**
     * Get OOO entries for a user
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;ooo_entries:read&lt;/code&gt;  Returns a list of OOO entries for the specified user.
     * @param user Globally unique identifier for the user to filter OOO entries by.
     * @param workspace Globally unique identifier for the workspace.
     * @param opts Optional parameters
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.start_date An ISO 8601 date string. Filters to OOO entries that overlap with or end after this date.
     * @param opts.end_date An ISO 8601 date string. Filters to OOO entries that overlap with or start before this date.
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    getOooEntriesWithHttpInfo(user: string, workspace: string, opts?: { 'limit'?: any; 'offset'?: string; 'start_date'?: any; 'end_date'?: any; 'opt_fields'?: any;  }): Promise<Collection | { response: any; data: any }>;

    /**
     * Get OOO entries for a user
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;ooo_entries:read&lt;/code&gt;  Returns a list of OOO entries for the specified user.
     * @param user Globally unique identifier for the user to filter OOO entries by.
     * @param workspace Globally unique identifier for the workspace.
     * @param opts Optional parameters
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.start_date An ISO 8601 date string. Filters to OOO entries that overlap with or end after this date.
     * @param opts.end_date An ISO 8601 date string. Filters to OOO entries that overlap with or start before this date.
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    getOooEntries(user: string, workspace: string, opts?: { 'limit'?: any; 'offset'?: string; 'start_date'?: any; 'end_date'?: any; 'opt_fields'?: any;  }): Promise<Collection | any>;

    /**
     * Get an OOO entry
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;ooo_entries:read&lt;/code&gt;  Returns the complete OOO entry record for a single OOO entry.
     * @param ooo_entry_gid Globally unique identifier for the OOO entry.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    getOooEntryWithHttpInfo(ooo_entry_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<{ response: any; data: any }>;

    /**
     * Get an OOO entry
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;ooo_entries:read&lt;/code&gt;  Returns the complete OOO entry record for a single OOO entry.
     * @param ooo_entry_gid Globally unique identifier for the OOO entry.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    getOooEntry(ooo_entry_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<any>;

    /**
     * Update an OOO entry
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;ooo_entries:write&lt;/code&gt;  An existing OOO entry can be updated by making a PUT request on the URL for that OOO entry. Only the fields provided in the &#x60;data&#x60; block will be updated; any unspecified fields will remain unchanged.  Returns the complete updated OOO entry record.
     * @param body The updated fields for the OOO entry.
     * @param ooo_entry_gid Globally unique identifier for the OOO entry.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    updateOooEntryWithHttpInfo(body: any, ooo_entry_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<{ response: any; data: any }>;

    /**
     * Update an OOO entry
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;ooo_entries:write&lt;/code&gt;  An existing OOO entry can be updated by making a PUT request on the URL for that OOO entry. Only the fields provided in the &#x60;data&#x60; block will be updated; any unspecified fields will remain unchanged.  Returns the complete updated OOO entry record.
     * @param body The updated fields for the OOO entry.
     * @param ooo_entry_gid Globally unique identifier for the OOO entry.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    updateOooEntry(body: any, ooo_entry_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<any>;

}
