/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";
import Collection = require("../utils/collection");

/**
* ProjectBriefs service.
* @module api/ProjectBriefsApi
* @version 3.1.11
*/
export class ProjectBriefsApi {
    /**
    * Constructs a new ProjectBriefsApi.
    * @alias module:api/ProjectBriefsApi
    * @class
    * @param apiClient Optional API client implementation to use, default to ApiClient.instance if unspecified.
    */
    constructor(apiClient?: ApiClient);

    apiClient: ApiClient;

    /**
     * Create a project brief
     * Creates a new project brief.  Returns the full record of the newly created project brief.
     * @param body The project brief to create.
     * @param project_gid Globally unique identifier for the project.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    createProjectBriefWithHttpInfo(body: any, project_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<{ response: any; data: any }>;

    /**
     * Create a project brief
     * Creates a new project brief.  Returns the full record of the newly created project brief.
     * @param body The project brief to create.
     * @param project_gid Globally unique identifier for the project.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    createProjectBrief(body: any, project_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<any>;

    /**
     * Delete a project brief
     * Deletes a specific, existing project brief.  Returns an empty data record.
     * @param project_brief_gid Globally unique identifier for the project brief.
     * @returns A Promise, with an object containing data and HTTP response
     */
    deleteProjectBriefWithHttpInfo(project_brief_gid: string): Promise<{ response: any; data: any }>;

    /**
     * Delete a project brief
     * Deletes a specific, existing project brief.  Returns an empty data record.
     * @param project_brief_gid Globally unique identifier for the project brief.
     * @returns A Promise
     */
    deleteProjectBrief(project_brief_gid: string): Promise<any>;

    /**
     * Get a project brief
     * Get the full record for a project brief.
     * @param project_brief_gid Globally unique identifier for the project brief.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    getProjectBriefWithHttpInfo(project_brief_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<{ response: any; data: any }>;

    /**
     * Get a project brief
     * Get the full record for a project brief.
     * @param project_brief_gid Globally unique identifier for the project brief.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    getProjectBrief(project_brief_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<any>;

    /**
     * Update a project brief
     * An existing project brief can be updated by making a PUT request on the URL for that project brief. Only the fields provided in the &#x60;data&#x60; block will be updated; any unspecified fields will remain unchanged.  Returns the complete updated project brief record.
     * @param body The updated fields for the project brief.
     * @param project_brief_gid Globally unique identifier for the project brief.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    updateProjectBriefWithHttpInfo(body: any, project_brief_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<{ response: any; data: any }>;

    /**
     * Update a project brief
     * An existing project brief can be updated by making a PUT request on the URL for that project brief. Only the fields provided in the &#x60;data&#x60; block will be updated; any unspecified fields will remain unchanged.  Returns the complete updated project brief record.
     * @param body The updated fields for the project brief.
     * @param project_brief_gid Globally unique identifier for the project brief.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    updateProjectBrief(body: any, project_brief_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<any>;

}
