/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";
import Collection = require("../utils/collection");

/**
* TimeTrackingCategories service.
* @module api/TimeTrackingCategoriesApi
* @version 3.1.11
*/
export class TimeTrackingCategoriesApi {
    /**
    * Constructs a new TimeTrackingCategoriesApi.
    * @alias module:api/TimeTrackingCategoriesApi
    * @class
    * @param apiClient Optional API client implementation to use, default to ApiClient.instance if unspecified.
    */
    constructor(apiClient?: ApiClient);

    apiClient: ApiClient;

    /**
     * Create a time tracking category
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;time_tracking_categories:write&lt;/code&gt;  Creates a new time tracking category in a given workspace.  Returns the record of the newly created time tracking category.
     * @param body Information about the time tracking category.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    createTimeTrackingCategoryWithHttpInfo(body: any, opts?: { 'opt_fields'?: any;  }): Promise<{ response: any; data: any }>;

    /**
     * Create a time tracking category
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;time_tracking_categories:write&lt;/code&gt;  Creates a new time tracking category in a given workspace.  Returns the record of the newly created time tracking category.
     * @param body Information about the time tracking category.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    createTimeTrackingCategory(body: any, opts?: { 'opt_fields'?: any;  }): Promise<any>;

    /**
     * Delete a time tracking category
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;time_tracking_categories:delete&lt;/code&gt;  Deletes a specific, existing time tracking category.  Returns an empty data record.
     * @param time_tracking_category_gid Globally unique identifier for the time tracking category.
     * @returns A Promise, with an object containing data and HTTP response
     */
    deleteTimeTrackingCategoryWithHttpInfo(time_tracking_category_gid: string): Promise<{ response: any; data: any }>;

    /**
     * Delete a time tracking category
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;time_tracking_categories:delete&lt;/code&gt;  Deletes a specific, existing time tracking category.  Returns an empty data record.
     * @param time_tracking_category_gid Globally unique identifier for the time tracking category.
     * @returns A Promise
     */
    deleteTimeTrackingCategory(time_tracking_category_gid: string): Promise<any>;

    /**
     * Get time tracking categories for a workspace
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;time_tracking_categories:read&lt;/code&gt;  Returns a paginated list of time tracking categories for a given workspace.
     * @param workspace Globally unique identifier for the workspace.
     * @param opts Optional parameters
     * @param opts.is_archived Filter by archived status. If not provided, defaults to returning non-archived categories.
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    getTimeTrackingCategoriesWithHttpInfo(workspace: string, opts?: { 'is_archived'?: boolean; 'limit'?: any; 'offset'?: string; 'opt_fields'?: any;  }): Promise<Collection | { response: any; data: any }>;

    /**
     * Get time tracking categories for a workspace
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;time_tracking_categories:read&lt;/code&gt;  Returns a paginated list of time tracking categories for a given workspace.
     * @param workspace Globally unique identifier for the workspace.
     * @param opts Optional parameters
     * @param opts.is_archived Filter by archived status. If not provided, defaults to returning non-archived categories.
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    getTimeTrackingCategories(workspace: string, opts?: { 'is_archived'?: boolean; 'limit'?: any; 'offset'?: string; 'opt_fields'?: any;  }): Promise<Collection | any>;

    /**
     * Get a time tracking category
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;time_tracking_categories:read&lt;/code&gt;  Returns the complete time tracking category record for a single time tracking category.
     * @param time_tracking_category_gid Globally unique identifier for the time tracking category.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    getTimeTrackingCategoryWithHttpInfo(time_tracking_category_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<{ response: any; data: any }>;

    /**
     * Get a time tracking category
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;time_tracking_categories:read&lt;/code&gt;  Returns the complete time tracking category record for a single time tracking category.
     * @param time_tracking_category_gid Globally unique identifier for the time tracking category.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    getTimeTrackingCategory(time_tracking_category_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<any>;

    /**
     * Get time tracking entries for a time tracking category
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;time_tracking_categories:read&lt;/code&gt;  Returns a paginated list of time tracking entries filtered by a given time tracking category.
     * @param time_tracking_category_gid Globally unique identifier for the time tracking category.
     * @param opts Optional parameters
     * @param opts.start_date The start date for filtering time tracking entries by their entry date.
     * @param opts.end_date The end date for filtering time tracking entries by their entry date.
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    getTimeTrackingEntriesForTimeTrackingCategoryWithHttpInfo(time_tracking_category_gid: string, opts?: { 'start_date'?: any; 'end_date'?: any; 'limit'?: any; 'offset'?: string; 'opt_fields'?: any;  }): Promise<Collection | { response: any; data: any }>;

    /**
     * Get time tracking entries for a time tracking category
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;time_tracking_categories:read&lt;/code&gt;  Returns a paginated list of time tracking entries filtered by a given time tracking category.
     * @param time_tracking_category_gid Globally unique identifier for the time tracking category.
     * @param opts Optional parameters
     * @param opts.start_date The start date for filtering time tracking entries by their entry date.
     * @param opts.end_date The end date for filtering time tracking entries by their entry date.
     * @param opts.limit Results per page. The number of objects to return per page. The value must be between 1 and 100.
     * @param opts.offset Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. *Note: You can only pass in an offset that was returned to you via a previously paginated request.*
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    getTimeTrackingEntriesForTimeTrackingCategory(time_tracking_category_gid: string, opts?: { 'start_date'?: any; 'end_date'?: any; 'limit'?: any; 'offset'?: string; 'opt_fields'?: any;  }): Promise<Collection | any>;

    /**
     * Update a time tracking category
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;time_tracking_categories:write&lt;/code&gt;  Updates the properties of a time tracking category. Only the fields provided in the &#x60;data&#x60; block will be updated; any unspecified fields will remain unchanged.  Returns the complete updated time tracking category record.
     * @param body The updated fields for the time tracking category.
     * @param time_tracking_category_gid Globally unique identifier for the time tracking category.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise, with an object containing data and HTTP response
     */
    updateTimeTrackingCategoryWithHttpInfo(body: any, time_tracking_category_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<{ response: any; data: any }>;

    /**
     * Update a time tracking category
     * &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;time_tracking_categories:write&lt;/code&gt;  Updates the properties of a time tracking category. Only the fields provided in the &#x60;data&#x60; block will be updated; any unspecified fields will remain unchanged.  Returns the complete updated time tracking category record.
     * @param body The updated fields for the time tracking category.
     * @param time_tracking_category_gid Globally unique identifier for the time tracking category.
     * @param opts Optional parameters
     * @param opts.opt_fields This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.
     * @returns A Promise
     */
    updateTimeTrackingCategory(body: any, time_tracking_category_gid: string, opts?: { 'opt_fields'?: any;  }): Promise<any>;

}
