/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Asana);
  }
}(this, function(expect, Asana) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AuditLogEventContext', function() {
      beforeEach(function() {
        instance = new Asana.AuditLogEventContext();
      });

      it('should create an instance of AuditLogEventContext', function() {
        // TODO: update the code to test AuditLogEventContext
        expect(instance).to.be.a(Asana.AuditLogEventContext);
      });

      it('should have the property context_type (base name: "context_type")', function() {
        // TODO: update the code to test the property context_type
        expect(instance).to.have.property('context_type');
        // expect(instance.context_type).to.be(expectedValueLiteral);
      });

      it('should have the property api_authentication_method (base name: "api_authentication_method")', function() {
        // TODO: update the code to test the property api_authentication_method
        expect(instance).to.have.property('api_authentication_method');
        // expect(instance.api_authentication_method).to.be(expectedValueLiteral);
      });

      it('should have the property client_ip_address (base name: "client_ip_address")', function() {
        // TODO: update the code to test the property client_ip_address
        expect(instance).to.have.property('client_ip_address');
        // expect(instance.client_ip_address).to.be(expectedValueLiteral);
      });

      it('should have the property user_agent (base name: "user_agent")', function() {
        // TODO: update the code to test the property user_agent
        expect(instance).to.have.property('user_agent');
        // expect(instance.user_agent).to.be(expectedValueLiteral);
      });

      it('should have the property oauth_app_name (base name: "oauth_app_name")', function() {
        // TODO: update the code to test the property oauth_app_name
        expect(instance).to.have.property('oauth_app_name');
        // expect(instance.oauth_app_name).to.be(expectedValueLiteral);
      });

    });
  });

}));
