/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Asana);
  }
}(this, function(expect, Asana) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PortfolioResponse', function() {
      beforeEach(function() {
        instance = new Asana.PortfolioResponse();
      });

      it('should create an instance of PortfolioResponse', function() {
        // TODO: update the code to test PortfolioResponse
        expect(instance).to.be.a(Asana.PortfolioResponse);
      });

      it('should have the property gid (base name: "gid")', function() {
        // TODO: update the code to test the property gid
        expect(instance).to.have.property('gid');
        // expect(instance.gid).to.be(expectedValueLiteral);
      });

      it('should have the property resource_type (base name: "resource_type")', function() {
        // TODO: update the code to test the property resource_type
        expect(instance).to.have.property('resource_type');
        // expect(instance.resource_type).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property color (base name: "color")', function() {
        // TODO: update the code to test the property color
        expect(instance).to.have.property('color');
        // expect(instance.color).to.be(expectedValueLiteral);
      });

      it('should have the property created_at (base name: "created_at")', function() {
        // TODO: update the code to test the property created_at
        expect(instance).to.have.property('created_at');
        // expect(instance.created_at).to.be(expectedValueLiteral);
      });

      it('should have the property created_by (base name: "created_by")', function() {
        // TODO: update the code to test the property created_by
        expect(instance).to.have.property('created_by');
        // expect(instance.created_by).to.be(expectedValueLiteral);
      });

      it('should have the property custom_field_settings (base name: "custom_field_settings")', function() {
        // TODO: update the code to test the property custom_field_settings
        expect(instance).to.have.property('custom_field_settings');
        // expect(instance.custom_field_settings).to.be(expectedValueLiteral);
      });

      it('should have the property current_status_update (base name: "current_status_update")', function() {
        // TODO: update the code to test the property current_status_update
        expect(instance).to.have.property('current_status_update');
        // expect(instance.current_status_update).to.be(expectedValueLiteral);
      });

      it('should have the property due_on (base name: "due_on")', function() {
        // TODO: update the code to test the property due_on
        expect(instance).to.have.property('due_on');
        // expect(instance.due_on).to.be(expectedValueLiteral);
      });

      it('should have the property custom_fields (base name: "custom_fields")', function() {
        // TODO: update the code to test the property custom_fields
        expect(instance).to.have.property('custom_fields');
        // expect(instance.custom_fields).to.be(expectedValueLiteral);
      });

      it('should have the property members (base name: "members")', function() {
        // TODO: update the code to test the property members
        expect(instance).to.have.property('members');
        // expect(instance.members).to.be(expectedValueLiteral);
      });

      it('should have the property owner (base name: "owner")', function() {
        // TODO: update the code to test the property owner
        expect(instance).to.have.property('owner');
        // expect(instance.owner).to.be(expectedValueLiteral);
      });

      it('should have the property start_on (base name: "start_on")', function() {
        // TODO: update the code to test the property start_on
        expect(instance).to.have.property('start_on');
        // expect(instance.start_on).to.be(expectedValueLiteral);
      });

      it('should have the property workspace (base name: "workspace")', function() {
        // TODO: update the code to test the property workspace
        expect(instance).to.have.property('workspace');
        // expect(instance.workspace).to.be(expectedValueLiteral);
      });

      it('should have the property permalink_url (base name: "permalink_url")', function() {
        // TODO: update the code to test the property permalink_url
        expect(instance).to.have.property('permalink_url');
        // expect(instance.permalink_url).to.be(expectedValueLiteral);
      });

      it('should have the property _public (base name: "public")', function() {
        // TODO: update the code to test the property _public
        expect(instance).to.have.property('_public');
        // expect(instance._public).to.be(expectedValueLiteral);
      });

      it('should have the property project_templates (base name: "project_templates")', function() {
        // TODO: update the code to test the property project_templates
        expect(instance).to.have.property('project_templates');
        // expect(instance.project_templates).to.be(expectedValueLiteral);
      });

    });
  });

}));
