/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Asana);
  }
}(this, function(expect, Asana) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Asana.AIStudioUsageAPIApi();
  });

  describe('(package)', function() {
    describe('AIStudioUsageAPIApi', function() {
      describe('getAiStudioRuns', function() {
        it('should call getAiStudioRuns successfully', function(done) {
          // TODO: uncomment, update parameter values for getAiStudioRuns call and complete the assertions
          /*
          var opts = {};

          instance.getAiStudioRuns(workspace_gid, opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(Asana.AiStudioRunResponseArray);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAiStudioSeats', function() {
        it('should call getAiStudioSeats successfully', function(done) {
          // TODO: uncomment, update parameter values for getAiStudioSeats call and complete the assertions
          /*
          var opts = {};

          instance.getAiStudioSeats(workspace_gid, opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(Asana.AiStudioSeatResponseArray);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
