/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Asana);
  }
}(this, function(expect, Asana) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Asana.GoalsApi();
  });

  describe('(package)', function() {
    describe('GoalsApi', function() {
      describe('addFollowers', function() {
        it('should call addFollowers successfully', function(done) {
          // TODO: uncomment, update parameter values for addFollowers call and complete the assertions
          /*
          var opts = {};

          instance.addFollowers(body, goal_gid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.GoalResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createGoal', function() {
        it('should call createGoal successfully', function(done) {
          // TODO: uncomment, update parameter values for createGoal call and complete the assertions
          /*
          var opts = {};

          instance.createGoal(body, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.GoalResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createGoalMetric', function() {
        it('should call createGoalMetric successfully', function(done) {
          // TODO: uncomment, update parameter values for createGoalMetric call and complete the assertions
          /*
          var opts = {};

          instance.createGoalMetric(body, goal_gid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.GoalResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteGoal', function() {
        it('should call deleteGoal successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteGoal call and complete the assertions
          /*

          instance.deleteGoal(goal_gid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.EmptyResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getGoal', function() {
        it('should call getGoal successfully', function(done) {
          // TODO: uncomment, update parameter values for getGoal call and complete the assertions
          /*
          var opts = {};

          instance.getGoal(goal_gid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.GoalResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getGoals', function() {
        it('should call getGoals successfully', function(done) {
          // TODO: uncomment, update parameter values for getGoals call and complete the assertions
          /*
          var opts = {};

          instance.getGoals(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.GoalResponseArray);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getParentGoalsForGoal', function() {
        it('should call getParentGoalsForGoal successfully', function(done) {
          // TODO: uncomment, update parameter values for getParentGoalsForGoal call and complete the assertions
          /*
          var opts = {};

          instance.getParentGoalsForGoal(goal_gid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.GoalResponseArray);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('removeFollowers', function() {
        it('should call removeFollowers successfully', function(done) {
          // TODO: uncomment, update parameter values for removeFollowers call and complete the assertions
          /*
          var opts = {};

          instance.removeFollowers(body, goal_gid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.GoalResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateGoal', function() {
        it('should call updateGoal successfully', function(done) {
          // TODO: uncomment, update parameter values for updateGoal call and complete the assertions
          /*
          var opts = {};

          instance.updateGoal(body, goal_gid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.GoalResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateGoalMetric', function() {
        it('should call updateGoalMetric successfully', function(done) {
          // TODO: uncomment, update parameter values for updateGoalMetric call and complete the assertions
          /*
          var opts = {};

          instance.updateGoalMetric(body, goal_gid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.GoalResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
