/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Asana);
  }
}(this, function(expect, Asana) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Asana.TeamsApi();
  });

  describe('(package)', function() {
    describe('TeamsApi', function() {
      describe('addUserForTeam', function() {
        it('should call addUserForTeam successfully', function(done) {
          // TODO: uncomment, update parameter values for addUserForTeam call and complete the assertions
          /*
          var opts = {};

          instance.addUserForTeam(body, team_gid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.TeamMembershipResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createTeam', function() {
        it('should call createTeam successfully', function(done) {
          // TODO: uncomment, update parameter values for createTeam call and complete the assertions
          /*
          var opts = {};

          instance.createTeam(body, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.TeamResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTeam', function() {
        it('should call getTeam successfully', function(done) {
          // TODO: uncomment, update parameter values for getTeam call and complete the assertions
          /*
          var opts = {};

          instance.getTeam(team_gid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.TeamResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTeamsForUser', function() {
        it('should call getTeamsForUser successfully', function(done) {
          // TODO: uncomment, update parameter values for getTeamsForUser call and complete the assertions
          /*
          var opts = {};

          instance.getTeamsForUser(user_gid, organization, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.TeamResponseArray);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTeamsForWorkspace', function() {
        it('should call getTeamsForWorkspace successfully', function(done) {
          // TODO: uncomment, update parameter values for getTeamsForWorkspace call and complete the assertions
          /*
          var opts = {};

          instance.getTeamsForWorkspace(workspace_gid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.TeamResponseArray);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('removeUserForTeam', function() {
        it('should call removeUserForTeam successfully', function(done) {
          // TODO: uncomment, update parameter values for removeUserForTeam call and complete the assertions
          /*

          instance.removeUserForTeam(body, team_gid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.EmptyResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateTeam', function() {
        it('should call updateTeam successfully', function(done) {
          // TODO: uncomment, update parameter values for updateTeam call and complete the assertions
          /*
          var opts = {};

          instance.updateTeam(body, team_gid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Asana.TeamResponseData);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
