/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Asana);
  }
}(this, function(expect, Asana) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Asana.TimeTrackingCategoriesApi();
  });

  describe('(package)', function() {
    describe('TimeTrackingCategoriesApi', function() {
      describe('createTimeTrackingCategory', function() {
        it('should call createTimeTrackingCategory successfully', function(done) {
          // TODO: uncomment, update parameter values for createTimeTrackingCategory call and complete the assertions
          /*
          var opts = {};

          instance.createTimeTrackingCategory(body, opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(Asana.TimeTrackingCategoryResponseData);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteTimeTrackingCategory', function() {
        it('should call deleteTimeTrackingCategory successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTimeTrackingCategory call and complete the assertions
          /*

          instance.deleteTimeTrackingCategory(time_tracking_category_gid).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(Asana.EmptyResponseData);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTimeTrackingCategories', function() {
        it('should call getTimeTrackingCategories successfully', function(done) {
          // TODO: uncomment, update parameter values for getTimeTrackingCategories call and complete the assertions
          /*
          var opts = {};

          instance.getTimeTrackingCategories(workspace, opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(Asana.TimeTrackingCategoryResponseArray);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTimeTrackingCategory', function() {
        it('should call getTimeTrackingCategory successfully', function(done) {
          // TODO: uncomment, update parameter values for getTimeTrackingCategory call and complete the assertions
          /*
          var opts = {};

          instance.getTimeTrackingCategory(time_tracking_category_gid, opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(Asana.TimeTrackingCategoryResponseData);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTimeTrackingEntriesForTimeTrackingCategory', function() {
        it('should call getTimeTrackingEntriesForTimeTrackingCategory successfully', function(done) {
          // TODO: uncomment, update parameter values for getTimeTrackingEntriesForTimeTrackingCategory call and complete the assertions
          /*
          var opts = {};

          instance.getTimeTrackingEntriesForTimeTrackingCategory(time_tracking_category_gid, opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(Asana.TimeTrackingEntryCompactArray);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateTimeTrackingCategory', function() {
        it('should call updateTimeTrackingCategory successfully', function(done) {
          // TODO: uncomment, update parameter values for updateTimeTrackingCategory call and complete the assertions
          /*
          var opts = {};

          instance.updateTimeTrackingCategory(body, time_tracking_category_gid, opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(Asana.TimeTrackingCategoryResponseData);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
